// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kscehdnecndpladhdcqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzY2VoZG5lY25kcGxhZGhkY3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NzE1NzUsImV4cCI6MjA2NzQ0NzU3NX0.uTABKKFN2rraw5Jyf-gT0oI7iUPAxhwKCwHl72EiuFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});